### ISSUE TITLE
Source for /Web/JS/mscorlib.js ?

### ISSUE THREAD

**Issue by davelab6** [mdileep/mutatorMath.gui#1]
Where is the source for https://raw.githubusercontent.com/mdileep/mutatorMath.gui/master/Web/JS/mscorlib.js ?

**Comment by mdileep** [comment]
It is part of  Script# 0.7.5.1 Package
https://www.nuget.org/packages/ScriptSharp/

**Comment by davelab6** [comment]
Okay great! :D I recommend including a full copy in this repo in a  `/third_party/` directory, but if you are moving away from script# anyway, no problem

**Comment by mdileep** [comment]
Script# is no longer part of this project.
